/*
 * receive raw serial data and write received data to a file
 *
 * This sample demonstrates raw serial communications using a
 * SyncLink serial card. The companion sample send-raw.c sends
 * raw serial data. Use both programs to send data between two serial cards
 * connected with a NULL modem (cross over cable) or other serial link.
 *
 * The sample is simple to clearly show basic programming concepts.
 * Use this code to start development of more complex applications.
 *
 * Overview:
 *
 * 1. open serial device (syscall open)
 * 2. configure serial device (syscall ioctl)
 * 3. receive data from serial device (syscall read)
 * 4. write received data to a file
 *
 * For more information about SyncLink specific programming refer to
 * the Programming.txt file included with the SyncLink software package.
 *
 *
 * Microgate and SyncLink are registered trademarks
 * of Microgate corporation.
 *
 * This code is released under the GNU General Public License (GPL)
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <stdio.h>
#include <memory.h>
#include <signal.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <linux/types.h>
#include <termios.h>
#include <errno.h>

#include "synclink.h"

#ifndef N_HDLC
#define N_HDLC 13
#endif

/*
 * set base clock frequency in cycles per second
 *
 * Data clocks are generated by dividing a fixed base clock by a 16-bit integer.
 * GT family base clock default is 14.7456MHz.
 *
 * Other base clocks (up to 33MHz) can be installed
 * at the factory by special order. Non default values require driver
 * configuration with the actual value so correct divisors are used for
 * a specified data rate.
 */
int set_base_clock(int fd, unsigned int freq)
{
	MGSL_PARAMS params;
	int rc;

	/* fields other than mode and clock_speed are ignored */
	params.mode = MGSL_MODE_BASE_CLOCK;
	params.clock_speed = freq;
	rc = ioctl(fd, MGSL_IOCSPARAMS, &params);
	if (rc < 0) {
		printf("set base clock frequency error=%d %s\n",
		       errno, strerror(errno));
	}
	return rc;
}

/* handle SIGINT - do nothing */
void sigint_handler(int sigid){}

int main(int argc, char* argv[])
{
	int fd;
	int rc;
	int ldisc = N_HDLC;
	MGSL_PARAMS params;
	int sigs;
	FILE *fp = NULL;
	int size = 4096;
	int count;
	unsigned char buf[4096];
	char *devname;

	if (argc > 1)
		devname = argv[1];
	else
		devname = "/dev/ttySLG0";

	printf("receive raw data on %s\n", devname);

	/* open file to save received data */
	fp = fopen("data", "wb");
	if (fp == NULL) {
		printf("fopen error=%d %s\n", errno, strerror(errno));
		return errno;
	}

	/* open serial device with O_NONBLOCK to ignore DCD input */
	fd = open(devname, O_RDWR | O_NONBLOCK, 0);
	if (fd < 0) {
		printf("open error=%d %s\n", errno, strerror(errno));
		return errno;
	}

	/*
	 * set N_HDLC line discipline (used for all synchronous modes)
	 *
	 * A line discipline is a software layer between a tty device driver
	 * and user application that performs intermediate processing,
	 * formatting, and buffering of data.
	 */
	rc = ioctl(fd, TIOCSETD, &ldisc);
	if(rc < 0) {
		printf("set line discipline error=%d %s\n",
		       errno, strerror(errno));
		return rc;
	}

	/* required only if custom base clock (not 14745600) installed */
//	if (set_base_clock(fd, 32000000) < 0)
//		return rc;

	/* get current device parameters */
	rc = ioctl(fd, MGSL_IOCGPARAMS, &params);
	if (rc < 0) {
		printf("ioctl(MGSL_IOCGPARAMS) error=%d %s\n",
		       errno, strerror(errno));
		return rc;
	}

	/*
	 * modify device parameters
	 *
	 * raw synchronous mode, loopback disabled, NRZ encoding
	 * data clocks sourced from clock input pins
	 * output 9600bps clock on auxclk output pin
	 * disable hardware CRC generation/checking
	 */

	params.mode = MGSL_MODE_RAW;
	params.loopback = 0;
	params.flags = HDLC_FLAG_RXC_RXCPIN + HDLC_FLAG_TXC_TXCPIN;
	params.encoding = HDLC_ENCODING_NRZ;
	params.clock_speed = 9600;
	params.crc_type = HDLC_CRC_NONE;

	/* set current device parameters */
	rc = ioctl(fd, MGSL_IOCSPARAMS, &params);
	if (rc < 0) {
		printf("ioctl(MGSL_IOCSPARAMS) error=%d %s\n",
		       errno, strerror(errno));
		return rc;
	}

	printf("Turn on RTS and DTR serial outputs\n");
	sigs = TIOCM_RTS + TIOCM_DTR;
	rc = ioctl(fd, TIOCMBIS, &sigs);
	if (rc < 0) {
		printf("assert DTR/RTS error=%d %s\n", errno, strerror(errno));
		return rc;
	}

	/* set device to blocking mode for reads and writes */
	fcntl(fd, F_SETFL, fcntl(fd,F_GETFL) & ~O_NONBLOCK);

	/* set ctrl-C to interrupt syscall but not exit program */
	printf("Press Ctrl-C to stop program.\n");
	signal(SIGINT, sigint_handler);
	siginterrupt(SIGINT, 1);

	/*
	 * disable and then enable receiver to discard any stale
	 * bytes in receive buffers
	 */
	ioctl(fd, MGSL_IOCRXENABLE, 0);
	ioctl(fd, MGSL_IOCRXENABLE, 1);

	/*
	 * read() returns data when a driver receive buffer (256 bytes) fills.
	 * At low data rates this may cause too much delay between receipt of
	 * a byte and that byte being returned to the application.
	 *
	 * Bits 31..16 of the MGSL_IOCRXENABLE ioctl argument specify
	 * the receive buffer fill level. When the specified
	 * number of bytes are received, read() returns the data. The value
	 * also controls the data transfer mode used by hardware (PIO or DMA).
	 *
	 * 128 to 256: DMA mode, value MUST be a multiple of 4
	 * 1   to 127: PIO mode, any value in this range is valid
	 * 0         : No operation - do not alter the fill level
	 *
	 * Use lower values as needed for lower data rates and lower latency.
	 * At high data rates PIO mode may cause data loss.
	 *
	 * Uncomment the line below to set the fill level to 8 bytes
	 * and select PIO mode.
	 */
//	ioctl(fd, MGSL_IOCRXENABLE, ((8 << 16) | 1));

	/*
	 * Raw serial mode does not use hardware synchronization
	 * so received data is not byte aligned. Data returned
	 * from read() may appear bit shifted. It is the responsibility of
	 * the application to detect and interpret data boundaries.
	 *
	 * Serial line bit order is least significant bit first.
	 * Each successive byte in buffer is sent LSB to MSB.
	 *
	 * Example 16 bits:
	 * serial line (first to last): 0000111111110000
	 * data from read(): buf[0]=0xf0 buf[1]=0x0f 
	 */

	for (;;) {

		/*
		 * get received data from serial device
		 *
		 * read() returns when a driver buffer fills.
		 * default driver buffer size is 256 bytes
		 */
		rc = read(fd, buf, size);
		if (rc < 0) {
			printf("read error=%d %s\n", errno, strerror(errno));
			break;
		}
		if (rc == 0) {
			printf("read returned with no data\n");
			continue;
		}
		printf("received %d bytes\n", rc);

		/* save received data to file */
		count = fwrite(buf, sizeof(char), rc, fp);
		if (count != rc) {
			printf("fwrite error=%d %s\n", errno, strerror(errno));
			break;
		}
		fflush(fp);
	}

	printf("Turn off RTS and DTR serial outputs\n");
	sigs = TIOCM_RTS + TIOCM_DTR;
	rc = ioctl(fd, TIOCMBIC, &sigs);
	if (rc < 0) {
		printf("negate DTR/RTS error=%d %s\n", errno, strerror(errno));
		return rc;
	}

	close(fd);
	fclose(fp);

	return 0;
}


