/*
 * send bisync data
 *
 * This sample demonstrates bisync communications using a
 * SyncLink serial card. The companion sample receive-bisync.c receives
 * bisync data. Use both programs to send data between two serial cards
 * connected with a NULL modem (cross over cable) or other serial link.
 *
 * The sample is simple to clearly show basic programming concepts.
 * Use this code to start development of more complex applications.
 *
 * Overview:
 *
 * 1. open serial device (syscall open)
 * 2. configure serial device (syscall ioctl)
 * 3. send data to serial device (syscall write)
 *
 * For more information about SyncLink specific programming refer to
 * the Programming.txt file included with the SyncLink software package.
 *
 * Microgate and SyncLink are registered trademarks
 * of Microgate corporation.
 *
 * This code is released under the GNU General Public License (GPL)
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <stdio.h>
#include <memory.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <linux/types.h>
#include <termios.h>
#include <errno.h>

#include "synclink.h"

#ifndef N_HDLC
#define N_HDLC 13
#endif

/*
 * set base clock frequency in cycles per second
 *
 * Data clocks are generated by dividing a fixed base clock by a 16-bit integer.
 * GT family base clock default is 14745600 (14.7456MHz)
 *
 * Other base clocks (up to 33MHz) can be installed
 * at the factory by special order. Non default values require driver
 * configuration with the actual value so correct divisors are used for
 * a specified data rate.
 */
int set_base_clock(int fd, unsigned int freq)
{
	MGSL_PARAMS params;
	int rc;

	/* fields other than mode and clock_speed are ignored */
	params.mode = MGSL_MODE_BASE_CLOCK;
	params.clock_speed = freq;
	rc = ioctl(fd, MGSL_IOCSPARAMS, &params);
	if (rc < 0) {
		printf("set base clock frequency error=%d %s\n",
		       errno, strerror(errno));
	}
	return rc;
}

int main(int argc, char* argv[])
{
	int fd;
	int rc;
	int sigs, idle;
	int ldisc = N_HDLC;
	MGSL_PARAMS params;
	int size = 1024;
	unsigned char buf[1024];
	char *devname;
	unsigned char syn1, syn2;

	if (argc > 1)
		devname = argv[1];
	else
		devname = "/dev/ttySLG0";

	printf("sending bisync data on %s\n", devname);

	/* open serial device with O_NONBLOCK to ignore DCD */
	fd = open(devname, O_RDWR | O_NONBLOCK, 0);
	if (fd < 0) {
		printf("open error=%d %s\n", errno, strerror(errno));
		return fd;
	}

	/* set N_HDLC line discipline (use for all synchronous modes) */
	rc = ioctl(fd, TIOCSETD, &ldisc);
	if(rc < 0) {
		printf("set ldisc error=%d %s\n", errno, strerror(errno));
		return rc;
	}

	/* required only if custom base clock (not 14745600) installed */
//	if (set_base_clock(fd, 32000000) < 0)
//		return rc;

	/* get current device parameters */
	rc = ioctl(fd, MGSL_IOCGPARAMS, &params);
	if (rc < 0) {
		printf("ioctl(MGSL_IOCGPARAMS) error=%d %s\n",
		       errno, strerror(errno));
		return rc;
	}

	/*
	 * modify device parameters
	 *
	 * bisync mode, loopback disabled, NRZ encoding
	 * data clocks sourced from clock input pins
	 * generate 9600 bps clock on auxclk output pin
	 * hardware CRC is not supported for bisync
	 *
	 * Parity generation/checking or CRC generation/checking
	 * must be performed by application if needed.
	 */

	params.mode = MGSL_MODE_BISYNC;
	params.loopback = 0;
	params.flags = HDLC_FLAG_RXC_RXCPIN + HDLC_FLAG_TXC_TXCPIN;
	params.encoding = HDLC_ENCODING_NRZ;
	params.clock_speed = 9600;
	params.crc_type = HDLC_CRC_NONE;

	/* set current device parameters */
	rc = ioctl(fd, MGSL_IOCSPARAMS, &params);
	if (rc < 0) {
		printf("ioctl(MGSL_IOCSPARAMS) error=%d %s\n",
		       errno, strerror(errno));
		return rc;
	}

	/*
         * set SYN1 and SYN2 sync characters
	 *
	 * These are example values only. The actual value needed for
	 * a specific application will be different.
	 */

	syn1 = 0x67;
	syn2 = 0x98;
	idle = HDLC_TXIDLE_CUSTOM_16 | (syn2 << 8) | syn1;
	rc = ioctl(fd, MGSL_IOCSTXIDLE, idle);
	if (rc < 0) {
		printf("ioctl(MGSL_IOCSTXIDLE) error=%d %s\n",
		       errno, strerror(errno));
		return rc;
	}

	/*
	 * initialize send buffer
	 *
	 * sync pattern
	 * start of block character (0x55)
	 * data (all zero)
	 * end of block character (0xaa)
	 *
	 * start/end of block characters used in this
	 * program are for demonstration only.
	 * Actual values are application dependent.
	 */
	memset(buf, 0, size);
	buf[0] = syn1;
	buf[1] = syn2;
	buf[2] = 0x55;
	buf[size-1] = 0xaa; 

	/* set device to blocking mode for reads and writes */
	fcntl(fd, F_SETFL, fcntl(fd,F_GETFL) & ~O_NONBLOCK);

	printf("Turn on RTS and DTR serial outputs\n");
	sigs = TIOCM_RTS + TIOCM_DTR;
	rc = ioctl(fd, TIOCMBIS, &sigs);
	if(rc < 0) {
		printf("assert DTR/RTS error=%d %s\n",
		       errno, strerror(errno));
		return rc;
	}

	printf("Sending %d bytes\n", size);
	rc = write(fd, buf, size);
	if (rc < 0) {
		printf("write error=%d %s\n", errno, strerror(errno));
		return rc;
	}

	printf("wait for all data sent...");
	/* chose method to wait for all data sent: blocked or polling */
#if 1
	/* block until all data sent */
	rc = tcdrain(fd);
	if (rc < 0) {
		printf("tcdrain error=%d %s\n", errno, strerror(errno));
	}
#else
	/* poll until all data sent */
	do {
		rc = ioctl(fd, TIOCOUTQ, &size);
		if (rc < 0) {
			printf("ioctl(TIOCOUTQ) error=%d %s\n",
			       errno, strerror(errno));
			break;
		}
	} while (size);
#endif
	printf("all data sent\n");

	/*
	 * disable transmitter to force transmit signal to constant 1
	 * otherwise transmitter sends repeated idle sync patterns
	 */
	ioctl(fd, MGSL_IOCTXENABLE, 0);

	/*
	 * keep auxclk clock output active for 2 seconds to give remote receiver
	 * a few extra clock cycles for internal processing of received data.
	 * If an external device supplies data clocks, this is not needed.
	 */
	sleep(2);

	printf("Turn off RTS and DTR serial outputs\n");
	sigs = TIOCM_RTS + TIOCM_DTR;
	rc = ioctl(fd, TIOCMBIC, &sigs);
	if (rc < 0) {
		printf("negate DTR/RTS error=%d %s\n",
		       errno, strerror(errno));
		return rc;
	}

	close(fd);

	return 0;
}

